In [ ]:
# FOLDER --- OIL

import os
import pandas as pd

# LOAD FOLDER OF DATA

from google.colab import drive
drive.mount('/content/drive', force_remount= True)

folder_path = "/content/drive/MyDrive/EvolucionMA/Data/PRODUCCIÓN-CYG-ANH/CRUDOANH"

# Lista de archivos válidos, sorted por año
archivos = [f for f in os.listdir(folder_path) if f.endswith((".xlsx", ".xls", ".csv"))]
archivos.sort(key=lambda x: int(x.split('-')[-1].split('.')[0]))

df_list = []

for archivo in archivos:
    ruta = os.path.join(folder_path, archivo)

    try:
        # EXTENSION TYPE AND LOAD
        if archivo.endswith(".xlsx") or archivo.endswith(".xls"):
            df_temp = pd.read_excel(ruta, skiprows=10)
        elif archivo.endswith(".csv"):
            df_temp = pd.read_csv(ruta, skiprows=10)

        # Normaliza columnas (strip y lower)
        df_temp.columns = df_temp.columns.str.strip().str.lower()

        # AD COLUMN YEAR (solo el número)
        year = int(archivo.split('-')[-1].split('.')[0])
        df_temp["año"] = year

        df_list.append(df_temp)
        print(f"✓ Cargado: {archivo}")
    except Exception as e:
        print(f"✗ Error: {archivo} - {e}")
        continue

# CREATE LIST OF NAMES
for i, nombre in enumerate(archivos):
    print(i, nombre)

# RENAME ALL COLUMNS USING CAPITAL LETTER
new_names = {
    'enero': 'ENERO',
    'febrero': 'FEBRERO',
    'marzo': 'MARZO',
    'abril': 'ABRIL',
    'mayo': 'MAYO',
    'junio': 'JUNIO',
    'julio': 'JULIO',
    'agosto': 'AGOSTO',
    'septiembre': 'SEPTIEMBRE',
    'octubre': 'OCTUBRE',
    'noviembre': 'NOVIEMBRE',
    'diciembre': 'DICIEMBRE',
    'departamento': 'DEPARTAMENTO',
    'operadora': 'OPERADORA',
    'campo': 'CAMPO',
    'contrato': 'CONTRATO',
    'municipio': 'MUNICIPIO',
    'año': 'AÑO'  # Renombra a mayús
}

for df in df_list:
    df.rename(columns=new_names, inplace=True)

# DATA NORMALIZATION
# TYPES OF DATA
for df in df_list:
    print("Año:", df["AÑO"].iloc[0])
    print(df.dtypes)
    print("-----------")

# DIMENSIONS
for df in df_list:
    print("Año:", df["AÑO"].iloc[0])
    print(df.shape)
    print("-----------")

# DELETE LAST 2 ROWS (si DF >2)
df_list = [df.iloc[:-2] for df in df_list if len(df) > 2]

# VALUES NULL
print("Valores Nulos:")
for df in df_list:
    print("Año:", df["AÑO"].iloc[0])
    print(df.isna().sum())
    print("-----------")

# WATCH PARTICULAR DF
print("Vista previa primer DF (ultimas 5 filas):")
df_list[9].tail(5)

Mounted at /content/drive
✓ Cargado: Crudo-2013.xlsx
✓ Cargado: Crudo-2014.xlsx
✓ Cargado: Crudo-2015.xlsx
✓ Cargado: Crudo-2016.xlsx
✓ Cargado: Crudo-2017.xlsx
✓ Cargado: Crudo-2018.xlsx
✓ Cargado: Crudo-2019.xlsx
✓ Cargado: Crudo-2020.xlsx
✓ Cargado: Crudo-2021.xlsx
✓ Cargado: Crudo-2022.xlsx
0 Crudo-2013.xlsx
1 Crudo-2014.xlsx
2 Crudo-2015.xlsx
3 Crudo-2016.xlsx
4 Crudo-2017.xlsx
5 Crudo-2018.xlsx
6 Crudo-2019.xlsx
7 Crudo-2020.xlsx
8 Crudo-2021.xlsx
9 Crudo-2022.xlsx
Año: 2013
DEPARTAMENTO     object
MUNICIPIO        object
OPERADORA        object
CAMPO            object
CONTRATO         object
ENERO           float64
FEBRERO         float64
MARZO           float64
ABRIL           float64
MAYO            float64
JUNIO           float64
JULIO           float64
AGOSTO          float64
SEPTIEMBRE      float64
OCTUBRE         float64
NOVIEMBRE       float64
DICIEMBRE       float64
AÑO               int64
dtype: object
-----------
Año: 2014
DEPARTAMENTO     object
MUNICIPIO        object
OPERADORA        object
CAMPO            object
CONTRATO         object
ENERO           float64
FEBRERO         float64
MARZO           float64
ABRIL           float64
MAYO            float64
JUNIO           float64
JULIO           float64
AGOSTO          float64
SEPTIEMBRE      float64
OCTUBRE         float64
NOVIEMBRE       float64
DICIEMBRE       float64
AÑO               int64
dtype: object
-----------
Año: 2015
DEPARTAMENTO     object
MUNICIPIO        object
OPERADORA        object
CAMPO            object
CONTRATO         object
ENERO           float64
FEBRERO         float64
MARZO           float64
ABRIL           float64
MAYO            float64
JUNIO           float64
JULIO           float64
AGOSTO          float64
SEPTIEMBRE      float64
OCTUBRE         float64
NOVIEMBRE       float64
DICIEMBRE       float64
AÑO               int64
dtype: object
-----------
Año: 2016
DEPARTAMENTO     object
MUNICIPIO        object
OPERADORA        object
CAMPO            object
CONTRATO         object
ENERO           float64
FEBRERO         float64
MARZO           float64
ABRIL           float64
MAYO            float64
JUNIO           float64
JULIO           float64
AGOSTO          float64
SEPTIEMBRE      float64
OCTUBRE         float64
NOVIEMBRE       float64
DICIEMBRE       float64
AÑO               int64
dtype: object
-----------
Año: 2017
DEPARTAMENTO     object
MUNICIPIO        object
OPERADORA        object
CAMPO            object
CONTRATO         object
ENERO           float64
FEBRERO         float64
MARZO           float64
ABRIL           float64
MAYO            float64
JUNIO           float64
JULIO           float64
AGOSTO          float64
SEPTIEMBRE      float64
OCTUBRE         float64
NOVIEMBRE       float64
DICIEMBRE       float64
AÑO               int64
dtype: object
-----------
Año: 2018
DEPARTAMENTO     object
MUNICIPIO        object
OPERADORA        object
CAMPO            object
CONTRATO         object
ENERO           float64
FEBRERO         float64
MARZO           float64
ABRIL           float64
MAYO            float64
JUNIO           float64
JULIO           float64
AGOSTO          float64
SEPTIEMBRE      float64
OCTUBRE         float64
NOVIEMBRE       float64
DICIEMBRE       float64
AÑO               int64
dtype: object
-----------
Año: 2019
DEPARTAMENTO     object
MUNICIPIO        object
OPERADORA        object
CONTRATO         object
CAMPO            object
ENERO           float64
FEBRERO         float64
MARZO           float64
ABRIL           float64
MAYO            float64
JUNIO           float64
JULIO           float64
AGOSTO          float64
SEPTIEMBRE      float64
OCTUBRE         float64
NOVIEMBRE       float64
DICIEMBRE       float64
AÑO               int64
dtype: object
-----------
Año: 2020
DEPARTAMENTO     object
MUNICIPIO        object
OPERADORA        object
CAMPO            object
CONTRATO         object
ENERO           float64
FEBRERO         float64
MARZO           float64
ABRIL           float64
MAYO            float64
JUNIO           float64
JULIO           float64
AGOSTO          float64
SEPTIEMBRE      float64
OCTUBRE         float64
NOVIEMBRE       float64
DICIEMBRE       float64
AÑO               int64
dtype: object
-----------
Año: 2021
DEPARTAMENTO     object
MUNICIPIO        object
OPERADORA        object
CAMPO            object
CONTRATO         object
ENERO           float64
FEBRERO         float64
MARZO           float64
ABRIL           float64
MAYO            float64
JUNIO           float64
JULIO           float64
AGOSTO          float64
SEPTIEMBRE      float64
OCTUBRE         float64
NOVIEMBRE       float64
DICIEMBRE       float64
AÑO               int64
dtype: object
-----------
Año: 2022
DEPARTAMENTO     object
MUNICIPIO        object
OPERADORA        object
CAMPO            object
CONTRATO         object
ENERO           float64
FEBRERO         float64
AÑO               int64
dtype: object
-----------
Año: 2013
(477, 18)
-----------
Año: 2014
(499, 18)
-----------
Año: 2015
(462, 18)
-----------
Año: 2016
(431, 18)
-----------
Año: 2017
(468, 18)
-----------
Año: 2018
(466, 18)
-----------
Año: 2019
(457, 18)
-----------
Año: 2020
(446, 18)
-----------
Año: 2021
(412, 18)
-----------
Año: 2022
(366, 8)
-----------
Valores Nulos:
Año: 2013
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       1
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2014
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           1
FEBRERO         1
MARZO           1
ABRIL           1
MAYO            1
JUNIO           1
JULIO           1
AGOSTO          1
SEPTIEMBRE      1
OCTUBRE         1
NOVIEMBRE       1
DICIEMBRE       1
AÑO             0
dtype: int64
-----------
Año: 2015
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           1
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2016
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2017
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2018
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2019
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CONTRATO        0
CAMPO           0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2020
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2021
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2022
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           1
FEBRERO         0
AÑO             0
dtype: int64
-----------
Vista previa primer DF (ultimas 5 filas):

,DEPARTAMENTO,MUNICIPIO,OPERADORA,CAMPO,CONTRATO,ENERO,FEBRERO,AÑO
359,META,CABUYARO,Frontera Energy Colombia Corp Sucursal Colombia,YATAY,GUATIQUIA,3329.91,3426.98,2022
360,CASANARE,MANI,Frontera Energy Colombia Corp Sucursal Colombia,YENAC,CASIMENA,379.52,395.34,2022
361,PUTUMAYO,PUERTO CAICEDO,ECOPETROL S.A.,YURILLA,NORORIENTE,75.76,44.68,2022
362,CESAR,SAN MARTÍN,"GRAN TIERRA ENERGY COLOMBIA, LLC",ZOE,MIDAS,0.00,2.16,2022
363,CASANARE,OROCUE,Frontera Energy Colombia Corp Sucursal Colombia,ZOPILOTE,CRAVOVIEJO,918.46,930.16,2022

In [ ]:
# ====================================================================
# LIMPIEZA MASIVA: RECORRER CADA AÑO Y SUSTITUIR LOS VALORES SUCIOS
# ====================================================================
valores_sucios= ["-",""," ","  "]
meses_cols = ['ENERO','FEBRERO','MARZO','ABRIL','MAYO','JUNIO',
                  'JULIO','AGOSTO','SEPTIEMBRE','OCTUBRE','NOVIEMBRE','DICIEMBRE']

for i, df in enumerate(df_list):
    print(f"\nProcesando año: {df['AÑO'].iloc[0]}")

    # Solo las que existan en este df
    meses_en_df = [col for col in meses_cols if col in df.columns]

    print(f"   → Columnas de meses encontradas: {len(meses_en_df)}")

    # 2. Reemplazar todos los valores sucios por NaN
    df[meses_en_df] = df[meses_en_df].replace(valores_sucios, pd.NA)

    # 3. Rellenar NaN con 0
    df[meses_en_df] = df[meses_en_df].fillna(0)

    # 4. Guardar el df limpio de vuelta en la lista
    df_list[i] = df

print("\n¡LIMPIEZA COMPLETA! Todos los años procesados.")

Procesando año: 2013
   → Columnas de meses encontradas: 12

Procesando año: 2014
   → Columnas de meses encontradas: 12

Procesando año: 2015
   → Columnas de meses encontradas: 12

Procesando año: 2016
   → Columnas de meses encontradas: 12

Procesando año: 2017
   → Columnas de meses encontradas: 12

Procesando año: 2018
   → Columnas de meses encontradas: 12

Procesando año: 2019
   → Columnas de meses encontradas: 12

Procesando año: 2020
   → Columnas de meses encontradas: 12

Procesando año: 2021
   → Columnas de meses encontradas: 12

Procesando año: 2022
   → Columnas de meses encontradas: 2

¡LIMPIEZA COMPLETA! Todos los años procesados.

/tmp/ipython-input-2333031773.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[meses_en_df] = df[meses_en_df].replace(valores_sucios, pd.NA)
/tmp/ipython-input-2333031773.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[meses_en_df] = df[meses_en_df].fillna(0)

In [ ]:
# =============================================
# MULTIPLICAR POR DÍAS DEL MES
# =============================================

import calendar

# Diccionario con los días de cada mes (año bisiesto = febrero 29)
def dias_del_mes(año, mes_nombre):
    mes_num = meses_cols.index(mes_nombre) + 1
    return calendar.monthrange(año, mes_num)[1]   # devuelve el último día del mes

# Recorremos cada año
for df in df_list:
    año = df['AÑO'].iloc[0]   # todos tienen el mismo año

    print(f"Procesando año {año}...")

    # Lista de columnas de meses que existen en este df
    meses = [col for col in df.columns if col in meses_cols]

    # Multiplicamos cada columna por sus días correspondientes
    for mes in meses:
        dias = dias_del_mes(año, mes)
        df[mes] = pd.to_numeric(df[mes], errors='coerce') * dias
        df[mes] = df[mes].round(0).astype('Int64')

    print(f"   → {año} convertido a producción mensual real (barriles totales por mes)")

print("\n¡Listo! Todos los DataFrames ahora tienen producción mensual real")

Procesando año 2013...
   → 2013 convertido a producción mensual real (barriles totales por mes)
Procesando año 2014...
   → 2014 convertido a producción mensual real (barriles totales por mes)
Procesando año 2015...
   → 2015 convertido a producción mensual real (barriles totales por mes)
Procesando año 2016...
   → 2016 convertido a producción mensual real (barriles totales por mes)
Procesando año 2017...
   → 2017 convertido a producción mensual real (barriles totales por mes)
Procesando año 2018...
   → 2018 convertido a producción mensual real (barriles totales por mes)
Procesando año 2019...
   → 2019 convertido a producción mensual real (barriles totales por mes)
Procesando año 2020...
   → 2020 convertido a producción mensual real (barriles totales por mes)
Procesando año 2021...
   → 2021 convertido a producción mensual real (barriles totales por mes)
Procesando año 2022...
   → 2022 convertido a producción mensual real (barriles totales por mes)

¡Listo! Todos los DataFrames ahora tienen producción mensual real

/tmp/ipython-input-3302960688.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[mes] = pd.to_numeric(df[mes], errors='coerce') * dias
/tmp/ipython-input-3302960688.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[mes] = df[mes].round(0).astype('Int64')

In [ ]:
#===========================
#    VALIDAR CONVERSION
#===========================

df_list[9].tail(5)

,DEPARTAMENTO,MUNICIPIO,OPERADORA,CAMPO,CONTRATO,ENERO,FEBRERO,AÑO
359,META,CABUYARO,Frontera Energy Colombia Corp Sucursal Colombia,YATAY,GUATIQUIA,103227,95955,2022
360,CASANARE,MANI,Frontera Energy Colombia Corp Sucursal Colombia,YENAC,CASIMENA,11765,11070,2022
361,PUTUMAYO,PUERTO CAICEDO,ECOPETROL S.A.,YURILLA,NORORIENTE,2349,1251,2022
362,CESAR,SAN MARTÍN,"GRAN TIERRA ENERGY COLOMBIA, LLC",ZOE,MIDAS,0,60,2022
363,CASANARE,OROCUE,Frontera Energy Colombia Corp Sucursal Colombia,ZOPILOTE,CRAVOVIEJO,28472,26044,2022

In [ ]:
for df in df_list:
    print("Año:", df["AÑO"].iloc[0])
    print(df.isna().sum())
    print("-----------")


for df in df_list:
    print("Año:", df["AÑO"].iloc[0])
    print(df.dtypes)
    print("-----------")

Año: 2013
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       1
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2014
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2015
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2016
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2017
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2018
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2019
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CONTRATO        0
CAMPO           0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2020
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2021
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
MARZO           0
ABRIL           0
MAYO            0
JUNIO           0
JULIO           0
AGOSTO          0
SEPTIEMBRE      0
OCTUBRE         0
NOVIEMBRE       0
DICIEMBRE       0
AÑO             0
dtype: int64
-----------
Año: 2022
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CAMPO           0
CONTRATO        0
ENERO           0
FEBRERO         0
AÑO             0
dtype: int64
-----------
Año: 2013
DEPARTAMENTO    object
MUNICIPIO       object
OPERADORA       object
CAMPO           object
CONTRATO        object
ENERO            Int64
FEBRERO          Int64
MARZO            Int64
ABRIL            Int64
MAYO             Int64
JUNIO            Int64
JULIO            Int64
AGOSTO           Int64
SEPTIEMBRE       Int64
OCTUBRE          Int64
NOVIEMBRE        Int64
DICIEMBRE        Int64
AÑO              int64
dtype: object
-----------
Año: 2014
DEPARTAMENTO    object
MUNICIPIO       object
OPERADORA       object
CAMPO           object
CONTRATO        object
ENERO            Int64
FEBRERO          Int64
MARZO            Int64
ABRIL            Int64
MAYO             Int64
JUNIO            Int64
JULIO            Int64
AGOSTO           Int64
SEPTIEMBRE       Int64
OCTUBRE          Int64
NOVIEMBRE        Int64
DICIEMBRE        Int64
AÑO              int64
dtype: object
-----------
Año: 2015
DEPARTAMENTO    object
MUNICIPIO       object
OPERADORA       object
CAMPO           object
CONTRATO        object
ENERO            Int64
FEBRERO          Int64
MARZO            Int64
ABRIL            Int64
MAYO             Int64
JUNIO            Int64
JULIO            Int64
AGOSTO           Int64
SEPTIEMBRE       Int64
OCTUBRE          Int64
NOVIEMBRE        Int64
DICIEMBRE        Int64
AÑO              int64
dtype: object
-----------
Año: 2016
DEPARTAMENTO    object
MUNICIPIO       object
OPERADORA       object
CAMPO           object
CONTRATO        object
ENERO            Int64
FEBRERO          Int64
MARZO            Int64
ABRIL            Int64
MAYO             Int64
JUNIO            Int64
JULIO            Int64
AGOSTO           Int64
SEPTIEMBRE       Int64
OCTUBRE          Int64
NOVIEMBRE        Int64
DICIEMBRE        Int64
AÑO              int64
dtype: object
-----------
Año: 2017
DEPARTAMENTO    object
MUNICIPIO       object
OPERADORA       object
CAMPO           object
CONTRATO        object
ENERO            Int64
FEBRERO          Int64
MARZO            Int64
ABRIL            Int64
MAYO             Int64
JUNIO            Int64
JULIO            Int64
AGOSTO           Int64
SEPTIEMBRE       Int64
OCTUBRE          Int64
NOVIEMBRE        Int64
DICIEMBRE        Int64
AÑO              int64
dtype: object
-----------
Año: 2018
DEPARTAMENTO    object
MUNICIPIO       object
OPERADORA       object
CAMPO           object
CONTRATO        object
ENERO            Int64
FEBRERO          Int64
MARZO            Int64
ABRIL            Int64
MAYO             Int64
JUNIO            Int64
JULIO            Int64
AGOSTO           Int64
SEPTIEMBRE       Int64
OCTUBRE          Int64
NOVIEMBRE        Int64
DICIEMBRE        Int64
AÑO              int64
dtype: object
-----------
Año: 2019
DEPARTAMENTO    object
MUNICIPIO       object
OPERADORA       object
CONTRATO        object
CAMPO           object
ENERO            Int64
FEBRERO          Int64
MARZO            Int64
ABRIL            Int64
MAYO             Int64
JUNIO            Int64
JULIO            Int64
AGOSTO           Int64
SEPTIEMBRE       Int64
OCTUBRE          Int64
NOVIEMBRE        Int64
DICIEMBRE        Int64
AÑO              int64
dtype: object
-----------
Año: 2020
DEPARTAMENTO    object
MUNICIPIO       object
OPERADORA       object
CAMPO           object
CONTRATO        object
ENERO            Int64
FEBRERO          Int64
MARZO            Int64
ABRIL            Int64
MAYO             Int64
JUNIO            Int64
JULIO            Int64
AGOSTO           Int64
SEPTIEMBRE       Int64
OCTUBRE          Int64
NOVIEMBRE        Int64
DICIEMBRE        Int64
AÑO              int64
dtype: object
-----------
Año: 2021
DEPARTAMENTO    object
MUNICIPIO       object
OPERADORA       object
CAMPO           object
CONTRATO        object
ENERO            Int64
FEBRERO          Int64
MARZO            Int64
ABRIL            Int64
MAYO             Int64
JUNIO            Int64
JULIO            Int64
AGOSTO           Int64
SEPTIEMBRE       Int64
OCTUBRE          Int64
NOVIEMBRE        Int64
DICIEMBRE        Int64
AÑO              int64
dtype: object
-----------
Año: 2022
DEPARTAMENTO    object
MUNICIPIO       object
OPERADORA       object
CAMPO           object
CONTRATO        object
ENERO            Int64
FEBRERO          Int64
AÑO              int64
dtype: object
-----------

In [ ]:
#===============================================================
# Lista donde guardaremos los DataFrames en el nuevo formato
#=============================================================
df_nuevo_formato = []

for df in df_list:
    # Convertimos a formato largo
    df_temp = pd.melt(
        df,
        id_vars=['DEPARTAMENTO', 'MUNICIPIO', 'OPERADORA', 'CONTRATO', 'CAMPO', 'AÑO'],
        value_vars=[m for m in meses_cols if m in df.columns],  # trae solo los meses que existen
        var_name='MES',
        value_name='PRODUCCION'
    )

    # ¡AQUÍ GUARDAMOS!
    df_nuevo_formato.append(df_temp)

    print(f"Convertido año {df['AÑO'].iloc[0]} → {df_temp.shape[0]} filas")

Convertido año 2013 → 5700 filas
Convertido año 2014 → 5964 filas
Convertido año 2015 → 5520 filas
Convertido año 2016 → 5148 filas
Convertido año 2017 → 5592 filas
Convertido año 2018 → 5568 filas
Convertido año 2019 → 5460 filas
Convertido año 2020 → 5328 filas
Convertido año 2021 → 4920 filas
Convertido año 2022 → 728 filas

In [ ]:
# VALUES NULL in df_nuevo_formato
print("Nulos después:")
for df in df_nuevo_formato:
    print("Año:", df["AÑO"].iloc[0])
    print(df.isna().sum())
    print("-----------")

Nulos después:
Año: 2013
DEPARTAMENTO     0
MUNICIPIO        0
OPERADORA       12
CONTRATO         0
CAMPO            0
AÑO              0
MES              0
PRODUCCION       0
dtype: int64
-----------
Año: 2014
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CONTRATO        0
CAMPO           0
AÑO             0
MES             0
PRODUCCION      0
dtype: int64
-----------
Año: 2015
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CONTRATO        0
CAMPO           0
AÑO             0
MES             0
PRODUCCION      0
dtype: int64
-----------
Año: 2016
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CONTRATO        0
CAMPO           0
AÑO             0
MES             0
PRODUCCION      0
dtype: int64
-----------
Año: 2017
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CONTRATO        0
CAMPO           0
AÑO             0
MES             0
PRODUCCION      0
dtype: int64
-----------
Año: 2018
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CONTRATO        0
CAMPO           0
AÑO             0
MES             0
PRODUCCION      0
dtype: int64
-----------
Año: 2019
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CONTRATO        0
CAMPO           0
AÑO             0
MES             0
PRODUCCION      0
dtype: int64
-----------
Año: 2020
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CONTRATO        0
CAMPO           0
AÑO             0
MES             0
PRODUCCION      0
dtype: int64
-----------
Año: 2021
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CONTRATO        0
CAMPO           0
AÑO             0
MES             0
PRODUCCION      0
dtype: int64
-----------
Año: 2022
DEPARTAMENTO    0
MUNICIPIO       0
OPERADORA       0
CONTRATO        0
CAMPO           0
AÑO             0
MES             0
PRODUCCION      0
dtype: int64
-----------

In [ ]:
#======================================
#      CREAR DATAFRAME TOTAL
#======================================


df_total = pd.concat(df_nuevo_formato, ignore_index=True)


print(f"DataFrame maestro creado: {df_total.shape[0]:,} filas × {df_total.shape[1]} columnas")
df_total.tail(5)

DataFrame maestro creado: 49,928 filas × 8 columnas

,DEPARTAMENTO,MUNICIPIO,OPERADORA,CONTRATO,CAMPO,AÑO,MES,PRODUCCION
49923,META,CABUYARO,Frontera Energy Colombia Corp Sucursal Colombia,GUATIQUIA,YATAY,2022,FEBRERO,95955
49924,CASANARE,MANI,Frontera Energy Colombia Corp Sucursal Colombia,CASIMENA,YENAC,2022,FEBRERO,11070
49925,PUTUMAYO,PUERTO CAICEDO,ECOPETROL S.A.,NORORIENTE,YURILLA,2022,FEBRERO,1251
49926,CESAR,SAN MARTÍN,"GRAN TIERRA ENERGY COLOMBIA, LLC",MIDAS,ZOE,2022,FEBRERO,60
49927,CASANARE,OROCUE,Frontera Energy Colombia Corp Sucursal Colombia,CRAVOVIEJO,ZOPILOTE,2022,FEBRERO,26044

In [ ]:
# =============================================
# LIMPIEZA PERFECTA: SIN TILDES
# =============================================

import unicodedata


def limpiar_sin_borrar_ñ(texto):
    if pd.isna(texto):
        return texto

    texto = str(texto)

    # Primero: protegemos la ñ y Ñ convirtiéndolas temporalmente
    texto = texto.replace('ñ', '###NYE###').replace('Ñ', '###NYE_MAYUS###')

    # Ahora sí normalizamos y quitamos tildes con seguridad
    texto = unicodedata.normalize('NFD', texto)
    texto = ''.join(c for c in texto if unicodedata.category(c) != 'Mn')

    # Devolvemos la ñ a su lugar
    texto = texto.replace('###NYE###', 'ñ').replace('###NYE_MAYUS###', 'Ñ')

    # Limpiamos y ponemos en mayúsculas (opcional)
    return texto.strip().upper()

# === Aplicar ===
print("Aplicando limpieza perfecta...")

df_total['DEPARTAMENTO'] = df_total['DEPARTAMENTO'].apply(limpiar_sin_borrar_ñ)
df_total['MUNICIPIO']    = df_total['MUNICIPIO'].apply(limpiar_sin_borrar_ñ)
df_total['CAMPO']        = df_total['CAMPO'].apply(limpiar_sin_borrar_ñ)
df_total['OPERADORA']    = df_total['OPERADORA'].apply(limpiar_sin_borrar_ñ)

# === VERIFICACIÓN 100% REAL ===
print("\nVERIFICACIÓN FINAL (debe salir con ñ):")
print("CAÑO LIMÓN →", df_total[df_total['CAMPO'].str.contains('CAÑO', case=False, na=False)]['CAMPO'].iloc[0])


print("\nDepartamentos limpios (sin tildes, con ñ):")
print("NARIÑO     →", df_total[df_total['DEPARTAMENTO'].str.contains('NARI', na=False)]['DEPARTAMENTO'].unique()[0])

Aplicando limpieza perfecta...

VERIFICACIÓN FINAL (debe salir con ñ):
CAÑO LIMÓN → CAÑO DUYA

Departamentos limpios (sin tildes, con ñ):
NARIÑO     → NARIÑO

In [ ]:
#EXPORTAR DT TOTAL
df_total.to_parquet('crudo_limpio.parquet', index=False)